spring:
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://localhost:8080/realms/demo
          jwk-set-uri: http://keycloak:8080/realms/demo/protocol/openid-connect/certs
#          issuer-uri: http://localhost:8080/realms/demo
#          jwk-set-uri: http://localhost:8080/realms/demo/protocol/openid-connect/certs

  profiles:
    active: docker

  application:
    name: customer-service


security:
  rules:
    - method: POST
      path: "/api/customers/users"
      role: "user:create"
    - method: GET
      path: "/api/customers/users"
      role: "user:read"
    - method: PUT
      path: "/api/customers/users/**"
      role: "user:edit"
    - method: DELETE
      path: "/api/customers/users/**"
      role: "user:delete"