services:
  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    networks:
      - app-network
    environment:
      - spring.profiles.active=native

  discovery-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3309:3306"
    networks:
      - app-network

  product-service:
    build: ./product-service
    container_name: product_container
    ports:
      - "8082:8080"
    environment:
      - DB_HOST=${PRODUCT_DB_HOST}
      - DB_PORT=${PRODUCT_DB_PORT}
      - DB_NAME=${PRODUCT_DB_NAME}
      - DB_USERNAME=${PRODUCT_DB_USERNAME}
      - DB_PASSWORD=${PRODUCT_DB_PASSWORD}
      - MSG=${PRODUCT_MSG}
      - SPRING_PROFILES_ACTIVE=${PRODUCT_PROFILE}
    networks:
      - app-network
    depends_on:
      - config-server
      - discovery-server
      - postgres

  customer-service:
    build: ./customer
    container_name: customer-container
    ports:
      - "9999:8080"
    networks:
      - app-network
    depends_on:
      - discovery-server
      - config-server
      - mysql
    environment:
      - DB_HOST=${CUSTOMER_DB_HOST}
      - DB_PORT=${CUSTOMER_DB_PORT}
      - DB_NAME=${CUSTOMER_DB_NAME}
      - DB_USERNAME=${CUSTOMER_DB_USERNAME}
      - DB_PASSWORD=${CUSTOMER_DB_PASSWORD}
      - MSG=${CUSTOMER_MSG}
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    build: ./api-gateway
    ports:
      - "9091:8080"
    networks:
      - app-network
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_started
      keycloak:
        condition: service_started
    environment:
      - spring.profiles.active=${GATEWAY_PROFILE}


  postgresKC:
    image: postgres:17
    container_name: postgres-kc
    restart: always
    environment:
      POSTGRES_DB: ${KC_DB}
      POSTGRES_USER: ${KC_USER}
      POSTGRES_PASSWORD: ${KC_PASSWORD}
    ports:
      - "6666:5432"
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    command: start-dev --hostname-strict=false --hostname-strict-https=false
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgresKC
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: ${KC_DB}
      KC_DB_USERNAME: ${KC_USER}
      KC_DB_PASSWORD: ${KC_PASSWORD}
      KC_HOSTNAME: localhost
    ports:
      - "8080:8080"
    depends_on:
      - postgresKC
    networks:
      - app-network
    volumes:
      - keycloak_data:/opt/keycloak/data

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  keycloak_data:
