services:
  # create service name
  db:
    image: postgres:17
    container_name: postgres-container-db
    restart: always
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservice-net

  # create service name
  product-service:
    build: ./product-service
    container_name: container_product_service
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=product_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - MSG="Hello from Docker!"
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - config-server-service-docker
      - eureka-server-service-docker
      - db
    networks:
      - microservice-net

  # create service name ( my-sql )
  db-mysql:
    image: mysql:8.0
    container_name: container_db_mysql
    restart: always
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql@12345
      MYSQL_DATABASE: customer_db
      MYSQL_USER: customer_user
      MYSQL_PASSWORD: Hell0W0rld
    networks:
      - microservice-net

  #create service name ( customer-service )
  customer-service:
    build: ./customer
    container_name: container_customer
    ports:
      - "9999:9999"
    environment:
      - DB_HOST=db-mysql
      - DB_PORT=3306
      - DB_NAME=customer_db
      - DB_USERNAME=root          # ✅ Added!
      - DB_PASSWORD=mysql@12345
      - MSG="HELLO FROM DOCKER CUSTOMER JAVA"
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db-mysql
      - config-server-service-docker
      - eureka-server-service-docker
    networks:
      - microservice-net


  # create service name
  api-gateway:
    build: ./api-gateway
    container_name: container_api_gateway
    ports:
      - "9091:9091"
    depends_on:
      - config-server-service-docker
      - eureka-server-service-docker
      - product-service
      - customer-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservice-net

  # create service name
  eureka-server-service-docker:
    build: ./eureka-server
    container_name: container_eureka_server
    ports:
      - "8761:8761"
    depends_on:
      - config-server-service-docker
    networks:
      - microservice-net

  # create service name
  config-server-service-docker:
    build: ./config-server
    container_name: container_config_server
    ports:
      - "8888:8888"
    networks:
      - microservice-net



networks:
  microservice-net:
    driver: bridge

volumes:
  postgres_data:
