spring:
  profiles:
    active: docker
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://keycloak:8080/realms/demo
          jwk-set-uri: http://keycloak:8080/realms/demo/protocol/openid-connect/certs
#          issuer-uri: http://localhost:8080/realms/demo
#          jwk-set-uri: http://localhost:8080/realms/demo/protocol/openid-connect/certs
  application:
    name: api-gateway


#  zipkin:
#    base-url: http://zipkin:9411

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0


jwt:
  auth:
    converter:
      resource-id: spring-boot-api
      principle-attribute: preferred_username