spring:
  config:
    import: optional:configserver:http://localhost:8888  # import config server

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true # register to eureka server
    registry-fetch-interval-seconds: 5 # Retry pulling registry every 5s if Eureka is down
    initial-instance-info-replication-interval-seconds: 5 # Retry registration every 5s if Eureka is down