spring:
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/demo
          jwk-set-uri: http://keycloak:8080/realms/demo/protocol/openid-connect/certs
  application:
    name: api-gateway


  zipkin:
    base-url: http://zipkin:9411


jwt:
  auth:
    converter:
      resource-id: micro-services-api
      principle-attribute: preferred_username