spring:
  datasource:
    username: keycloak_user
    password: keycloak@1234
    url: jdbc:postgresql://postgres:5432/keycloak_db
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/local