server:
  port: 8888

spring:
#  profiles:
#    active: native
  application:
    name: config-server

  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config/customer/
            - classpath:/config/product/
            - classpath:/config/api-gateway/
